# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1469d8b77aecb7e0a324a8d7c0ff9176a4434d09b9a1ed2e03aa6351e6332813a8334c897023d6a6325439e46cb08f884b3d99e3c5ba0ed1920dcf2b58d39e0a

test:
  secret_key_base: 2f256fbb21f65dd1be819c14d27d1cf6ec7d738ef7a0452272523f87ec5f966ff2c75dd89c042f42684684164dc547fba2b1eaa581b2e9bdbce077bdb85c97ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
